---
version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-2022
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Secured*"
    ports:
      - 1433:1433
    volumes:
      - petsitter_volume:/var/opt/mssql
    networks:
      - petsitter_net

volumes:
  petsitter_volume:

networks:
  petsitter_net: